#!/bin/bash
# BLISSS BLISS
repo init -u --depth=1 https://github.com/Miku-UI/manifesto -b Vampire_v3 --git-lfs
# Sync source
/opt/crave/resync.sh

# --- BUILD ---

export BUILD_USERNAME='sarkazz!?'
export BUILD_HOSTNAME=Ulinux

# Set up environment
. build/envsetup.sh

# Choose a target
lunch miku_earth-bp4a-userdebug

# To build
make diva

# Upload files to github
echo "Upload to github will be started..."
if [ -f out/target/product/earth/*.zip ]; then
  bash /opt/crave/github-actions/upload.sh 'miku' 'earth' 'https://github.com/inoo-droid/Earth_Release' 'miku15.2' 
fi
echo "done"
